[workspace.package]
version = "3.10.0"

[workspace]
resolver = "2"
members = [
    "render-conjure",
    "witchcraft-server",
    "witchcraft-server-config",
    "witchcraft-server-ete",
    "witchcraft-server-macros",
]

[patch.crates-io]
conjure-codegen = { git = "https://github.com/palantir/conjure-rust", branch = "dependabot/cargo/http-1.0.0" }
conjure-error = { git = "https://github.com/palantir/conjure-rust", branch = "dependabot/cargo/http-1.0.0" }
conjure-http = { git = "https://github.com/palantir/conjure-rust", branch = "dependabot/cargo/http-1.0.0" }
conjure-object = { git = "https://github.com/palantir/conjure-rust", branch = "dependabot/cargo/http-1.0.0" }
conjure-serde = { git = "https://github.com/palantir/conjure-rust", branch = "dependabot/cargo/http-1.0.0" }
conjure-runtime = { git = "https://github.com/palantir/conjure-rust-runtime", branch = "upgrades" }
conjure-runtime-config = { git = "https://github.com/palantir/conjure-rust-runtime", branch = "upgrades" }
